export const products = [
  // CLOTHES
  {
    id: "1",
    name: "Premium T-Shirt Oversized Cotton Casual Wear",
    price: "₱399",
    image: "https://picsum.photos/300?tshirt",
    category: "Clothes",
    sold: "1.2k sold",
    rating: "5.0",
    location: "Las Piñas City, Metro Manila",
  },
  {
    id: "2",
    name: "Classic Hoodie Jacket Unisex",
    price: "₱799",
    image: "https://picsum.photos/300?hoodie",
    category: "Clothes",
    sold: "850 sold",
    rating: "4.8",
    location: "Manila City",
  },
  {
    id: "3",
    name: "Summer Casual Polo Shirt",
    price: "₱499",
    image: "https://picsum.photos/300?poloshirt",
    category: "Clothes",
    sold: "670 sold",
    rating: "4.9",
    location: "Makati City",
  },

  // SHOES
  {
    id: "4",
    name: "Running Shoes Sports Edition",
    price: "₱1,299",
    image: "https://picsum.photos/300?runningshoes",
    category: "Shoes",
    sold: "890 sold",
    rating: "4.8",
    location: "Makati City, Metro Manila",
  },
  {
    id: "5",
    name: "Classic White Sneakers",
    price: "₱999",
    image: "https://picsum.photos/300?whitesneakers",
    category: "Shoes",
    sold: "1.5k sold",
    rating: "4.9",
    location: "Pasig City",
  },
  {
    id: "6",
    name: "Outdoor Hiking Shoes",
    price: "₱1,799",
    image: "https://picsum.photos/300?hikingshoes",
    category: "Shoes",
    sold: "430 sold",
    rating: "4.7",
    location: "Quezon City",
  },

  // ELECTRONICS
  {
    id: "7",
    name: "Bluetooth Speaker Premium Sound Quality",
    price: "₱899",
    image: "https://picsum.photos/300?speaker",
    category: "Electronics",
    sold: "2.4k sold",
    rating: "4.9",
    location: "Quezon City, Metro Manila",
  },
  {
    id: "8",
    name: "Wireless Earbuds Pro",
    price: "₱599",
    image: "https://picsum.photos/300?earbuds",
    category: "Electronics",
    sold: "1.8k sold",
    rating: "4.8",
    location: "Taguig City",
  },
  {
    id: "9",
    name: "Smart Watch Fitness Tracker",
    price: "₱1,499",
    image: "https://picsum.photos/300?smartwatch",
    category: "Electronics",
    sold: "980 sold",
    rating: "4.7",
    location: "Pasay City",
  },

  // BEAUTY
  {
    id: "10",
    name: "Matte Lipstick Long Lasting",
    price: "₱199",
    image: "https://picsum.photos/300?lipstick",
    category: "Beauty",
    sold: "540 sold",
    rating: "4.7",
    location: "Pasig City",
  },
  {
    id: "11",
    name: "Vitamin C Brightening Serum",
    price: "₱350",
    image: "https://picsum.photos/300?serum",
    category: "Beauty",
    sold: "1.1k sold",
    rating: "4.9",
    location: "Manila City",
  },
  {
    id: "12",
    name: "Luxury Facial Care Set",
    price: "₱799",
    image: "https://picsum.photos/300?skincare",
    category: "Beauty",
    sold: "700 sold",
    rating: "4.8",
    location: "Cavite",
  },

  // GROCERY
  {
    id: "13",
    name: "Premium Rice 5kg",
    price: "₱280",
    image: "https://picsum.photos/300?rice",
    category: "Grocery",
    sold: "2.4k sold",
    rating: "4.9",
    location: "Quezon City",
  },
  {
    id: "14",
    name: "Organic Fresh Vegetables Bundle",
    price: "₱350",
    image: "https://picsum.photos/300?vegetables",
    category: "Grocery",
    sold: "980 sold",
    rating: "4.8",
    location: "Las Piñas City",
  },
  {
    id: "15",
    name: "Coffee Premium Blend Pack",
    price: "₱450",
    image: "https://picsum.photos/300?coffee",
    category: "Grocery",
    sold: "1.3k sold",
    rating: "4.9",
    location: "Marikina City",
  },

  // BAGS
  {
    id: "16",
    name: "Premium Leather Backpack",
    price: "₱899",
    image: "https://picsum.photos/300?backpack",
    category: "Bags",
    sold: "600 sold",
    rating: "4.8",
    location: "Manila City",
  },
  {
    id: "17",
    name: "Travel Shoulder Bag",
    price: "₱499",
    image: "https://picsum.photos/300?shoulderbag",
    category: "Bags",
    sold: "820 sold",
    rating: "4.7",
    location: "Makati City",
  },
  {
    id: "18",
    name: "Fashion Mini Hand Bag",
    price: "₱699",
    image: "https://picsum.photos/300?handbag",
    category: "Bags",
    sold: "400 sold",
    rating: "4.9",
    location: "Pasig City",
  },

  // ACCESSORIES
  {
    id: "19",
    name: "Stainless Steel Watch",
    price: "₱899",
    image: "https://picsum.photos/300?watch",
    category: "Accessories",
    sold: "1k sold",
    rating: "4.8",
    location: "Taguig City",
  },
  {
    id: "20",
    name: "Classic Sunglasses",
    price: "₱299",
    image: "https://picsum.photos/300?sunglasses",
    category: "Accessories",
    sold: "750 sold",
    rating: "4.7",
    location: "Manila City",
  },
  {
    id: "21",
    name: "Fashion Bracelet Set",
    price: "₱199",
    image: "https://picsum.photos/300?bracelet",
    category: "Accessories",
    sold: "500 sold",
    rating: "4.9",
    location: "Caloocan City",
  },
];
